CREATE TABLE [dbo].[xcust_linfox_rcv_pr_int_tbl](
	[store_code] [varchar](8) NOT NULL,
	[po_number] [varchar](25) NOT NULL,
	[supplier_code] [varchar](8) NOT NULL,
	[delivery_date] [varchar](255) NULL,
	[subinventory_code] [varchar](10) NULL,
	[order_qty] [decimal](18, 0) NOT NULL,
	[confirm_qty] [decimal](18, 0) NOT NULL,
	[item_code] [varchar](7) NULL,
	[order_date] [varchar](255) NULL,
	[po_status] [varchar](1) NULL,
	[conf_delivery_date] [varchar](255) NULL,
	[Validate_flag] [varchar](1) NOT NULL,
	[process_flag] [varchar](1) NOT NULL,
	[error_message] [varchar](240) NULL,
	[creation_by] [int] NOT NULL,
	[creation_date] [varchar](255) NOT NULL,
	[last_update_date] [date] NULL,
	[last_update_by] [int] NULL,
	[file_name] [varchar](50) NOT NULL,
	[request_date] [date] NULL,
	[diriver_to_organization] [varchar](150) NULL,
	[deriver_to_location] [varchar](60) NULL,
	[erp_subinventory_code] [varchar](10) NULL,
	[ERP_ITEM_CODE] [varchar](300) NULL,
	[AGREEEMENT_NUMBER] [varchar](30) NULL,
	[AGREEMENT_LINE_NUMBER] [int] NULL,
	[PRICE] [numeric](18, 2) NULL,
	[ITEM_CATEGORY_NAME] [varchar](250) NULL,
	[SUPPLIER_SITE_CODE] [varchar](240) NULL,
	[ACC_SEG1] [varchar](25) NULL,
	[ACC_SEG2] [varchar](25) NULL,
	[ACC_SEG3] [varchar](25) NULL,
	[ACC_SEG4] [varchar](25) NULL,
	[ACC_SEG5] [varchar](25) NULL,
	[ACC_SEG6] [varchar](25) NULL,
	[uom_code] [varchar](5) NOT NULL,
	[DELIVERY_INSTRUCTION] [varchar](60) NULL
) ON [PRIMARY]

