update XCUST_BLANKET_AGREEMENT_HEADER_TBL 
set SUPPLIER_CODE = 'S72', MIN_RELEASE_AMT = 1, AGREEMENT_AMT = 50000
where DESCRIPTION = 'Agreement 1234';

update XCUST_BLANKET_AGREEMENT_LINES_TBL
set ITem_code = 'THF2152', RElease_amt = 600000
where DESCRIPTION = 'Agreement 1234'